#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false 
bspc config focus_follows_pointer true

bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
~/.config/bspwm/autostart &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/bin/low_bat_notifier.sh
